### ISSUE TITLE
Solana explorer

### ISSUE THREAD

**Issue by abourget** [streamingfast/substreams-explorers#2]
Clone the Ethereum one, build the `map_block_full` and `map_transaction_full` with a simple filter, outputting the same model as what the chain offers (so import the solana spkg).

Goal is to be able to use something like:

```
substreams gui -e mainnet.eth.streamingfast.io:443 https://storage.googleapis.com/substreams-registry/spkg/ethereum-explorer-v0.1.1.spkg map_block_full --start-block 1397588 --stop-block +1
```

just for inspecting stuff.

Even better if one can filter a given transaction, or a given thing, and have a reduced block, so there's less confusion between transactions when debugging.

This way, we can also add that to streamingfast.io in the widget.. would show multichain support directly on the front page, and make the data model discoverable.

https://github.com/streamingfast/substreams-explorers

**Comment by Eduard-Voiculescu** [comment]
This was done by @colindickson
