### ISSUE TITLE
Error running solana-explorer substream

### ISSUE THREAD

**Issue by Tarunshrma** [streamingfast/substreams-explorers#9]
Hello,

I have tried to run the solana-explorer substreams as mentioned in substream documentation https://substreams.streamingfast.io/tutorials/solana/explore-solana. However I am getting error at **Substreams GUI** terminal window that says 

```
_"read next message: rpc error: code = Unauthenticated desc = required authorization token not found. Please provide a valid JWT token via 'authorization' header
or or an API key via 'x-api-key' header"_

```

On readme file I got a link from documentation to get the required auth-token however the link is broken.  I am attaching the screenshot's for reference.

<img width="1431" alt="Screenshot 2024-08-09 at 8 05 24 PM" src="https://github.com/user-attachments/assets/5529b434-486f-40a4-b0c7-860abe40295f">
<img width="980" alt="Screenshot 2024-08-09 at 8 06 16 PM" src="https://github.com/user-attachments/assets/a883f620-c290-4dd0-a995-8b6af00702b1">
<img width="1624" alt="Screenshot 2024-08-09 at 8 06 20 PM" src="https://github.com/user-attachments/assets/a6c546f7-e24e-4653-af62-dc6dda8803c0">

I am planning to use Substream based subgraph indexing for **Solana Blockchain** for my custom program but did not get much help.

**Comment by maoueh** [comment]
@Tarunshrma You probably didn't export the environment variable or something like that. It will be easier to help on our Discord https://discord.gg/4k6aQ49S.

Please join it so we can live support you.

**Comment by maoueh** [comment]
I see also that you got a 404 found, the correct page should be https://substreams.streamingfast.io/documentation/consume/authentication

**Comment by maoueh** [comment]
I've just edited the wrong links in the different explorer(s)
